version: '3'

services:
  app:
    build: .
    command: npm start
    ports: 
      - "3035:3000"
    volumes: 
      - .:/usr/app

mysql:
  container_name: "data-node"
  image: mysql:5.7.31
  command: --default-authentification-plugin=mysql_native_password 
  restart: always
  ports:
    - ""